import { sveltekit } from '@sveltejs/kit/vite';
import tailwindcss from '@tailwindcss/vite';
import { resolve } from 'path';
import { defineConfig } from 'vite';

/**
 * Paraglide is generated by `bun scripts/regenerate-paraglide.mjs` at the
 * repo root rather than via the inlang vite plugin. The plugin fetches its
 * modules from a CDN at boot time, which is fragile under bun and not
 * worth the dependency for our static message catalogues.
 */
export default defineConfig({
	resolve: {
		alias: {
			'@be-certain/ui': resolve(__dirname, '../../packages/ui')
		}
	},
	plugins: [tailwindcss(), sveltekit()],
	build: {
		target: 'chrome108'
	},
	optimizeDeps: {
		// vtk.js + pako + fflate ship per-file ESM modules; let vite pre-bundle
		// the common ones so dev-server first-paint isn't stalled.
		include: ['pako', 'fflate']
	}
});
