// The user manual structure: task-oriented sections, each with a screenshot, a
// localized title + body (what the controls do and produce), and the inventory ids
// it documents. The Help page renders this; coverage.test.ts asserts that every
// INVENTORY id appears in exactly one section's `covers` (the goal's STOP condition).
//
// titleKey → help.tasks.<id>.title, bodyKey → help.tasks.<id>.body (i18n catalog).
// shot → static/manual/<shot>.png (dark-mode screenshot generated by manual-shots.e2e.ts).

import { isExperimentalId } from './inventory';

export interface ManualSection {
	id: string;
	titleKey: string;
	bodyKey: string;
	shot: string;
	covers: string[];
	/** Wholly-experimental section (CBCT/IOS 3D, photos, FMX): only shown in-app when
	 *  the viewer has Labs access; always omitted from the manual PDF. */
	experimental?: boolean;
}

const section = (
	id: string,
	shot: string,
	covers: string[],
	experimental = false
): ManualSection => ({
	id,
	titleKey: `help.tasks.${id}.title`,
	bodyKey: `help.tasks.${id}.body`,
	shot,
	covers,
	experimental
});

export const MANUAL: ManualSection[] = [
	section('home', 'home', [
		'home.dropzone',
		'home.createPatient',
		'home.search',
		'home.recent',
		'home.viewAll',
		'home.metrics'
	]),
	section('signin', 'signin', [
		'auth.signin.email',
		'auth.signin.password',
		'auth.signin.submit',
		'auth.signin.useCode',
		'auth.signin.usePassword',
		'auth.otp.sendCode',
		'auth.otp.code',
		'auth.otp.verify',
		'auth.otp.requestNew',
		'auth.link.createAccount',
		'auth.link.forgot',
		'auth.forgot.email',
		'auth.forgot.submit',
		'auth.forgot.back',
		'modals.consent.agree',
		'modals.consent.decline'
	]),
	section('signup', 'signup', [
		'auth.signup.name',
		'auth.signup.email',
		'auth.signup.confirm',
		'auth.signup.acceptTerms',
		'auth.signup.submit'
	]),
	section('workspace', 'workspace', [
		'workspace.sidebar.home',
		'workspace.sidebar.help',
		'workspace.sidebar.theme',
		'workspace.sidebar.userMenu',
		'workspace.menu.account',
		'workspace.menu.billing',
		'workspace.menu.settings',
		'workspace.menu.logout',
		'workspace.topbar.search',
		'workspace.topbar.history',
		'workspace.topbar.historyClear'
	]),
	section('studies', 'studies', [
		'studies.newStudy',
		'studies.patientCard',
		'studies.retry',
		'studies.clearSearch',
		'studies.pager'
	]),
	section('newStudy', 'upload', [
		'upload.modXray',
		'upload.modPanoramic',
		'upload.modCbct',
		'upload.modIos',
		'upload.modPhoto',
		'upload.name',
		'upload.dob',
		'upload.phonePhoto',
		'upload.browse',
		'upload.dropzone',
		'upload.remove',
		'upload.run',
		'upload.cancel'
	]),
	section('quickAnalyze', 'quickdrop', [
		'quick.drag',
		'quick.paste',
		'quick.screenCapture',
		'quick.assign.nameIt',
		'quick.assign.addExisting',
		'quick.assign.keep',
		'quick.assign.nameInput',
		'quick.assign.dobInput',
		'quick.assign.save',
		'quick.assign.search',
		'quick.assign.assign',
		'quick.assign.cancel'
	]),
	section('xrayTools', 'viewer2d', [
		'viewer2d.back',
		'viewer2d.fmxToggle',
		'viewer2d.tabXrays',
		'viewer2d.tabPhotos',
		'viewer2d.prev',
		'viewer2d.next',
		'viewer2d.fullFmx',
		'viewer2d.arrowKeys',
		'viewer2d.zoomIn',
		'viewer2d.zoomOut',
		'viewer2d.fit',
		'viewer2d.actualSize',
		'viewer2d.magnifier',
		'viewer2d.rotateRight',
		'viewer2d.flipH',
		'viewer2d.flipV',
		'viewer2d.adjust',
		'viewer2d.invert',
		'viewer2d.toothNumbers',
		'viewer2d.anatomy',
		'viewer2d.resetAdjust',
		'viewer2d.pan',
		'viewer2d.wheelZoom',
		'viewer2d.adjust.brightness',
		'viewer2d.adjust.contrast',
		'viewer2d.adjust.sharpness',
		'viewer2d.adjust.saturation',
		'viewer2d.adjust.reset'
	]),
	section('findings', 'findings', [
		'viewer2d.findings.allPathology',
		'viewer2d.findings.classToggle',
		'viewer2d.editDetections'
	]),
	section('reportPrintout', 'printout', ['viewer2d.report']),
	section('patientRecord', 'patient', [
		'patient.back',
		'patient.fmxToggle',
		'patient.dateFilter',
		'patient.tabXrays',
		'patient.tab3d',
		'patient.tabPhotos',
		'patient.edit',
		'patient.delete',
		'patient.addStudy',
		'patient.printout',
		'patient.openStudy',
		'patient.deleteStudy',
		'fmx.grid.slot'
	]),
	section('settings', 'settings', [
		'settings.theme',
		'settings.language',
		'settings.toothNumbering',
		'settings.measurementUnit',
		'settings.enable3d'
	]),
	section('account', 'account', [
		'account.name',
		'account.mobile',
		'account.address',
		'account.save'
	]),
	section('billing', 'billing', [
		'billing.subscribe',
		'billing.cancel',
		'billing.cancelled',
		'modals.paywall.viewPlans',
		'modals.paywall.notNow'
	]),

	// ── Experimental (Labs-gated) — kept at the bottom; shown in-app only when the
	// account has Labs access, and omitted from the manual PDF entirely. ─────────
	section('fmxNavigator', 'fmxnav', ['fmx.navigator', 'fmx.navigator.pick'], true),
	section(
		'photos',
		'photos',
		['photos.add', 'photos.view', 'photos.delete', 'photos.navigate', 'photos.close'],
		true
	),
	section(
		'cbctNavigate',
		'cbct-mpr',
		[
			'cbct.back',
			'cbct.viewMpr',
			'cbct.view3d',
			'cbct.viewPanoramic',
			'cbct.viewReport',
			'cbct.runSegmentation',
			'cbct.tool.crosshair',
			'cbct.tool.pan',
			'cbct.tool.wl',
			'cbct.tool.measure',
			'cbct.tool.angle',
			'cbct.tool.annotate',
			'cbct.tool.slab',
			'cbct.tool.toggleCrosshair',
			'cbct.tool.resetWL',
			'cbct.tool.resetAll',
			'cbct.mpr.sliceSlider',
			'cbct.mpr.wheelScrub',
			'cbct.mpr.arrowScrub',
			'cbct.mpr.maximize',
			'cbct.window',
			'cbct.level',
			'cbct.reduceNoise'
		],
		true
	),
	section(
		'cbct3d',
		'cbct-3d',
		[
			'cbct.vol.orbit',
			'cbct.vol.gizmo',
			'cbct.vol.selectTooth',
			'cbct.vol.openTooth',
			'cbct.layers.toggle'
		],
		true
	),
	section(
		'cbctPanoramic',
		'cbct-pano',
		[
			'cbct.pano.crosshair',
			'cbct.pano.pan',
			'cbct.pano.ruler',
			'cbct.pano.slab',
			'cbct.pano.zoomFit',
			'cbct.pano.overlays'
		],
		true
	),
	section(
		'cbctReport',
		'cbct-report',
		[
			'cbct.report.print',
			'cbct.report.sign',
			'cbct.report.categoryChips',
			'cbct.report.toothChart',
			'cbct.report.selectTeeth',
			'cbct.card.condition',
			'cbct.card.comment',
			'cbct.card.approve',
			'cbct.modal.sort',
			'cbct.modal.close'
		],
		true
	),
	section(
		'readIos',
		'ios',
		[
			'ios.back',
			'ios.runSegmentation',
			'ios.view.anterior',
			'ios.view.posterior',
			'ios.view.rightBuccal',
			'ios.view.leftBuccal',
			'ios.view.occlusalUpper',
			'ios.view.occlusalLower',
			'ios.wireframe',
			'ios.measure',
			'ios.clearMeasure',
			'ios.screenshot',
			'ios.resetView',
			'ios.layers.all',
			'ios.layers.upper',
			'ios.layers.lower',
			'ios.layers.toothToggle',
			'ios.toothChart',
			'ios.selectTooth'
		],
		true
	)
];

/** The manual sections to actually render, given viewer access.
 *  - In-app, a viewer with Labs (`labs`) sees everything; without it, experimental
 *    sections are dropped and experimental controls are filtered out of core sections.
 *  - For the PDF (`pdf: true`) experimental content is ALWAYS omitted, regardless of
 *    Labs — the printed manual documents the baseline product only.
 *  Section order is preserved (experimental sections live at the end of MANUAL), and a
 *  section left empty after filtering is dropped. */
export function visibleSections({ labs, pdf }: { labs: boolean; pdf: boolean }): ManualSection[] {
	const showExperimental = labs && !pdf;
	return MANUAL.filter((s) => showExperimental || !s.experimental)
		.map((s) =>
			showExperimental ? s : { ...s, covers: s.covers.filter((id) => !isExperimentalId(id)) }
		)
		.filter((s) => s.covers.length > 0);
}
